"""
Project Euler Problem 45
========================

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle     T[n]=n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal   P[n]=n(3n-1)/2  1, 5, 12, 22, 35, ...
Hexagonal    H[n]=n(2n-1)    1, 6, 15, 28, 45, ...

It can be verified that T[285] = P[165] = H[143] = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from __future__ import division
import math


# All hexagonal Numbers are Triangles
# using the quadratic formula we can check if
# the hexagonal number is a pentagonal number
i = 144
result = 0
while True:
    result = i*(2*i - 1)
    check = (1 + math.sqrt(1 + 24*result)) / 6
    if check == int(check):
        break
    i += 1
print(result)